
export const SET_LOADING = 'SET_LOADING';
export const HIDE_LOADER = 'HIDE_LOADER';

export const FETCH_COMPANIES = 'FETCH_COMPANIES';
export const GET_COMPANIES = 'GET_COMPANIES';

export const FETCH_COMPANY = 'FETCH_COMPANY';
export const SET_DEVIDENTS = 'SET_DEVIDENTS';
export const SET_PROMOTIONS = 'SET_PROMOTIONS';